---
prod:
  hosts:
    talos:
      ansible_host: talos
      ansible_port: 4733
      ansible_user: cameron
      ansible_ssh_private_key_file: ~/.ssh/talos_key

    italos:
      ansible_host: 24.159.105.10
      ansible_port: 4733
      ansible_user: cameron
      ansible_ssh_private_key_file: ~/.ssh/talos_key

dev:
  hosts:
    talosdev:
      ansible_connection: local
      ansible_user: vagrant
      # ansible_host: 127.0.0.1
      # ansible_port: 2222
      # ansible_ssh_private_key_file: "/mnt/c/Users/camer/megasync/media server/talos.dev/.vagrant/machines/default/virtualbox/private_key"
# https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html
