---
- name: Create /mnt points
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: "0777"
  with_items:
    - "{{ snapraid_parity_disks }}"
    - "{{ snapraid_data_disks }}"
    - "{{ fstab_mergerfs }}"
    # - "{{ extra_mountpoints }}"

- name: Mount disks
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ item.source }}"
    fstype: "{{ item.fs }}"
    opts: "{{ item.opts }}"
    # change to 'mounted' to auto mount
    state: present
  with_items:
    - "{{ snapraid_parity_disks }}"
    - "{{ snapraid_data_disks }}"
    # - "{{ extra_mountpoints }}"
  when: item.path != '/mnt/storage'

- name: Mount mergerfs array
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ item.source }}"
    fstype: "{{ item.fs }}"
    opts: "{{ item.opts }}"
    # change to 'mounted' to auto mount
    state: present
  with_items:
    - "{{ fstab_mergerfs }}"
