---
- name: Set hostname
  ansible.builtin.hostname:
    name: talos

- name: Disks
  ansible.builtin.include_tasks: disks.yml
  tags:
    - disks

- name: File-sharing
  ansible.builtin.include_tasks: file-sharing.yml
  tags:
    - file-sharing
    - disks

### Telegraf docker fix
- name: Add telegraf to docker group
  ansible.builtin.user:
    name: telegraf
    append: true
    groups:
      - docker
  notify: Restart telegraf

### Wireguard/Tailscale
- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    reload: yes
- name: Enable IPv6 forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: 1
    reload: yes
