---
# tasks file for ansible-telegraf

- name: Install on RedHat
  ansible.builtin.include_tasks: RedHat.yml
  when:
    - ansible_os_family == "RedHat" and not telegraf_agent_docker

- name: Install on Debian
  ansible.builtin.include_tasks: Debian.yml
  when:
    - ansible_os_family == "Debian" and not telegraf_agent_docker
  tags:
    - telegraf
    - packages

- name: Install on Suse
  ansible.builtin.include_tasks: Suse.yml
  when: ansible_os_family == "Suse" and not telegraf_agent_docker

- name: Install on FreeBSD
  ansible.builtin.include_tasks: FreeBSD.yml
  when:
    - ansible_os_family == "FreeBSD" and not telegraf_agent_docker

- name: Install on MacOS
  ansible.builtin.include_tasks: MacOS.yml
  when:
    - ansible_os_family == "Darwin" and not telegraf_agent_docker

- ansible.builtin.include_tasks: docker.yml
  when: telegraf_agent_docker

- name: Configure Telegraf
  ansible.builtin.include_tasks: configure_linux.yml
  when:
    - ansible_os_family not in ['Windows', 'Darwin']

- name: Install / Configure telegraf on Windows
  ansible.builtin.include_tasks: configure_windows.yml
  when:
    - ansible_os_family == "Windows" and not telegraf_agent_docker

- name: Install / Configure telegraf on MacOS
  ansible.builtin.include_tasks: configure_macos.yml
  when:
    - ansible_os_family == "Darwin" and not telegraf_agent_docker
