---
- name: Ensure python pip is available
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Install apprise
  ansible.builtin.pip:
    name: apprise
    extra_args: --break-system-packages
  become: true
