---
- name: Install cronie
  ansible.builtin.package:
    name: cronie
    state: present

- name: Enable cronie service
  ansible.builtin.systemd:
    name: cronie
    state: restarted
    enabled: true
